---
title: Doctor Tal Friedman ND
baseURL: "/"
params:
  layout_style: grid
  palette: green
  header:
    title: Dr Tal Friedman ND
    logo_img: images/logo.png
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links: []
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
